Repository unchain-tech/UNCHAIN-projects, pull requests merged in 2023-08, with the labels that each got.

#429 Update XRPL-NFT-Maker
  docs/XRPL-NFT-Maker/ja/section-3/lesson-2_webアプリケーションからNFTをmintしよう.md
  docs/XRPL-NFT-Maker/ja/section-4/lesson-1_Webアプリをアップデートしよう.md
Labels: documentation

#433 Update/ETH-DAO
  docs/ETH-DAO/ja/section-1/lesson-2_ローカル環境を構築しよう.md
  docs/ETH-DAO/ja/section-1/lesson-3_ウォレットに接続してみよう.md
  docs/ETH-DAO/ja/section-1/lesson-4_ネットワークの警告を出そう.md
  docs/ETH-DAO/ja/section-2/lesson-1_thirdwebのセットアップをしよう.md
  docs/ETH-DAO/ja/section-2/lesson-2_NFTをデプロイしよう.md
  docs/ETH-DAO/ja/section-2/lesson-3_NFTのメタデータを設定しよう.md
  docs/ETH-DAO/ja/section-2/lesson-4_NFTをミントしてみよう.md
  docs/ETH-DAO/ja/section-3/lesson-1_ガバナンストークンのコントラクトをデプロイしよう.md
  docs/ETH-DAO/ja/section-3/lesson-2_会員限定のダッシュボードをつくろう.md
  docs/ETH-DAO/ja/section-3/lesson-3_トレジャリーと投票コントラクトをつくろう.md
  docs/ETH-DAO/ja/section-3/lesson-4_プロポーザルに投票できるようにしよう.md
  docs/ETH-DAO/ja/section-4/lesson-1_管理権限を解除しよう.md
Labels: bug, documentation

#434 Feature/eth dapp/update
  docs/ETH-dApp/ja/section-1/lesson-1_ローカル環境でイーサリアムネットワークを立ち上げよう.md
  docs/ETH-dApp/ja/section-1/lesson-2_Solidityでスマートコントラクトを作成しよう.md
  docs/ETH-dApp/ja/section-1/lesson-4_スマートコントラクトにデータを保存しよう.md
  docs/ETH-dApp/ja/section-1/lesson-5_ローカル環境にコントラクトをデプロイしよう.md
  docs/ETH-dApp/ja/section-2/lesson-1_コントラクトをテストネットにデプロイしよう.md
  docs/ETH-dApp/ja/section-3/lesson-1_ブロックチェーン上にデータを保存しよう.md
  docs/ETH-dApp/ja/section-3/lesson-2_ユーザーにETHを送ろう.md
  docs/ETH-dApp/ja/section-4/lesson-1_WEBアプリに抽選機能を実装しよう.md
  docs/ETH-dApp/ja/section-4/lesson-2_UIをアップグレードして自分だけのオリジナルアプリを作ろう.md
Labels: bug, documentation, enhancement

#438 feat: update test scripts and output
  docs/ETH-DAO/ja/section-4/lesson-1_管理権限を解除しよう.md
Labels: documentation, enhancement
