Repository unchain-tech/UNCHAIN-projects, pull requests merged in 2023-06, with the labels that each got.

#405 Feature/Solana-Online-Store/refactor
  docs/Solana-Online-Store/ja/section-1/lesson-1_環境を構築しよう.md
  docs/Solana-Online-Store/ja/section-1/lesson-2_ウォレット接続ボタンを実装しよう.md
  docs/Solana-Online-Store/ja/section-1/lesson-3_ダウンロード機能を実装しよう.md
  docs/Solana-Online-Store/ja/section-2/lesson-1_Solanaでトランザクションを送信しよう.md
  docs/Solana-Online-Store/ja/section-2/lesson-2_SOLをUSDCに変更しよう.md
  docs/Solana-Online-Store/ja/section-2/lesson-3_注文情報を保存しよう.md
  docs/Solana-Online-Store/ja/section-2/lesson-4_購入機能を実装しよう.md
  docs/Solana-Online-Store/ja/section-3/lesson-1_商品を追加しよう.md
  docs/Solana-Online-Store/ja/section-4/lesson-1_仕上げをしよう.md
  public/images/Solana-Online-Store/section-1/1_1_2.png
  public/images/Solana-Online-Store/section-1/1_1_3.png
  public/images/Solana-Online-Store/section-1/1_1_4.png
  public/images/Solana-Online-Store/section-1/1_1_5.jpg
  public/images/Solana-Online-Store/section-4/4_1_1.png
  public/images/Solana-Online-Store/section-4/4_1_3.png
Labels: documentation, enhancement

#404 Feature/Solana-Wallet/refactor
  docs/Solana-Wallet/ja/section-0/lesson-2_環境構築をしよう.md
  docs/Solana-Wallet/ja/section-1/lesson-1_ウォレットを作成しよう.md
  docs/Solana-Wallet/ja/section-1/lesson-2_ウォレットを復元・インポートしよう.md
  docs/Solana-Wallet/ja/section-2/lesson-1_残高を取得しよう.md
  docs/Solana-Wallet/ja/section-3/lesson-1_エアドロップ機能を作ろう.md
  docs/Solana-Wallet/ja/section-3/lesson-2_送金機能を作ろう.md
  docs/Solana-Wallet/ja/section-3/lesson-3_VercelにWEBサイトをデプロイしよう.md
  public/images/Solana-Wallet/section-0/0_2_2.png
  public/images/Solana-Wallet/section-0/0_2_3.png
  public/images/Solana-Wallet/section-0/0_2_4.png
  public/images/Solana-Wallet/section-3/3_3_1.png
Labels: documentation

#402 Fix/eth nft maker
  docs/ETH-NFT-Maker/ja/section-1/lesson-2_hardhatを設定しよう.md
  docs/ETH-NFT-Maker/ja/section-1/lesson-3_スマートコントラクトをつくってみよう.md
  docs/ETH-NFT-Maker/ja/section-1/lesson-4_NFTを発行するスマートコントラクトを作ろう.md
  docs/ETH-NFT-Maker/ja/section-2/lesson-3_ipfsをつかってmintしよう！.md
  docs/ETH-NFT-Maker/ja/section-3/lesson-1_スマコンを呼び出そう.md
  docs/ETH-NFT-Maker/ja/section-3/lesson-1_フロントのsetting.md
  docs/ETH-NFT-Maker/ja/section-3/lesson-2_webアプリケーションからNFTをmintしよう.md
  docs/ETH-NFT-Maker/ja/section-4/lesson-1_Webアプリをアップデートしよう.md
  docs/ETH-NFT-Maker/ja/section-4/lesson-2_Vercelを使ってアプリをデプロイしよう.md
  public/images/ETH-NFT-Maker/section-1/1_2_1.png
  public/images/ETH-NFT-Maker/section-1/1_2_2.png
  public/images/ETH-NFT-Maker/section-1/1_2_3.png
  public/images/ETH-NFT-Maker/section-4/4_2_1.png
  public/images/ETH-NFT-Maker/section-4/4_2_2.png
  public/images/ETH-NFT-Maker/section-4/4_2_3.png
  public/images/ETH-NFT-Maker/section-4/4_2_4.png
  public/metadata/ETH-NFT-Maker/description.json
Labels: documentation

#407 Feature/Solana-NFT-Drop/refactor
  docs/Solana-NFT-Drop/ja/section-1/lesson-2_Phantom Walletを連携しよう.md
  docs/Solana-NFT-Drop/ja/section-1/lesson-3_webサイトにウォレット連携ボタンを実装しよう.md
  docs/Solana-NFT-Drop/ja/section-2/lesson-1_Solanaの開発環境を構築しよう.md
  docs/Solana-NFT-Drop/ja/section-2/lesson-2_NFT画像を準備しよう.md
  docs/Solana-NFT-Drop/ja/section-2/lesson-3_NFTをdevnetにデプロイしよう.md
  docs/Solana-NFT-Drop/ja/section-3/lesson-1_WEBアプリからCandyMachineを呼び出す.md
  docs/Solana-NFT-Drop/ja/section-3/lesson-2_NFTをミントするボタンを作成しよう.md
  docs/Solana-NFT-Drop/ja/section-4/lesson-1_カウントダウンタイマーと売り切れUIを実装しよう.md
  docs/Solana-NFT-Drop/ja/section-4/lesson-2_WEBアプリを完成させよう.md
  public/images/Solana-NFT-Drop/section-1/1_2_1.png
  public/images/Solana-NFT-Drop/section-1/1_2_2.png
  public/images/Solana-NFT-Drop/section-1/1_2_3.png
  public/images/Solana-NFT-Drop/section-1/1_2_4.png
  public/images/Solana-NFT-Drop/section-1/1_2_5.png
  public/images/Solana-NFT-Drop/section-1/1_2_6.png
  public/images/Solana-NFT-Drop/section-1/1_2_7.png
  public/images/Solana-NFT-Drop/section-4/4_1_5.png
  public/images/Solana-NFT-Drop/section-4/4_2_1.png
  public/images/Solana-NFT-Drop/section-4/4_2_4.png
Labels: documentation, enhancement

#408 Feature/XRPL-NFT-Maker/update
  docs/XRPL-NFT-Maker/ja/section-3/lesson-1_フロントエンドの準備.md
  docs/XRPL-NFT-Maker/ja/section-3/lesson-2_webアプリケーションからNFTをmintしよう.md
  public/images/XRPL-NFT-Maker/section-3/3_1_2.png
  public/images/XRPL-NFT-Maker/section-3/3_1_3.png
  public/images/XRPL-NFT-Maker/section-3/3_1_4.png
  public/images/XRPL-NFT-Maker/section-3/3_2_5.png
  public/images/XRPL-NFT-Maker/section-3/3_2_6.png
  public/images/XRPL-NFT-Maker/section-3/3_2_7.png
Labels: documentation, enhancement

#399 Fix/eth dapp
  docs/ETH-dApp/ja/section-1/lesson-1_ローカル環境でイーサリアムネットワークを立ち上げよう.md
  docs/ETH-dApp/ja/section-1/lesson-2_Solidityでスマートコントラクトを作成しよう.md
  docs/ETH-dApp/ja/section-1/lesson-3_コントラクトをローカル環境でコンパイルして実行しよう.md
  docs/ETH-dApp/ja/section-1/lesson-4_スマートコントラクトにデータを保存しよう.md
  docs/ETH-dApp/ja/section-1/lesson-5_ローカル環境にコントラクトをデプロイしよう.md
  docs/ETH-dApp/ja/section-2/lesson-1_コントラクトをテストネットにデプロイしよう.md
  docs/ETH-dApp/ja/section-2/lesson-2_ウォレットをWEBアプリに接続しよう.md
  docs/ETH-dApp/ja/section-2/lesson-3_WEBアプリからコントラクトを呼び出そう.md
  docs/ETH-dApp/ja/section-3/lesson-1_ブロックチェーン上にデータを保存しよう.md
  docs/ETH-dApp/ja/section-3/lesson-2_ユーザーにETHを送ろう.md
  docs/ETH-dApp/ja/section-4/lesson-1_WEBアプリに抽選機能を実装しよう.md
  docs/ETH-dApp/ja/section-4/lesson-2_UIをアップグレードして自分だけのオリジナルアプリを作ろう.md
  public/images/ETH-dApp/section-1/1_1_1.png
  public/images/ETH-dApp/section-1/1_1_2.png
  public/images/ETH-dApp/section-1/1_1_3.png
  public/images/ETH-dApp/section-1/1_1_4.png
  public/images/ETH-dApp/section-2/2_2_5.png
  public/images/ETH-dApp/section-4/4_2_4.png
  public/images/ETH-dApp/section-4/4_2_5.png
  public/images/ETH-dApp/section-4/4_2_6.png
  public/images/ETH-dApp/section-4/4_2_7.png
Labels: documentation

#400 Feature/eth nft collection/refactor
  docs/ETH-NFT-Collection/ja/section-1/lesson-2_ローカル環境でイーサリアムネットワークを立ち上げよう.md
  docs/ETH-NFT-Collection/ja/section-1/lesson-3_ローカル環境でNFTをmintしよう.md
  docs/ETH-NFT-Collection/ja/section-1/lesson-4_NFTを発行するスマートコントラクトを作ろう.md
  docs/ETH-NFT-Collection/ja/section-2/lesson-2_静的なSVGデータを作ろう.md
  docs/ETH-NFT-Collection/ja/section-2/lesson-3_ブロックチェーン上で動的なSVGを作ろう.md
  docs/ETH-NFT-Collection/ja/section-3/lesson-3_WEBアプリからコントラクトを呼び出そう.md
  docs/ETH-NFT-Collection/ja/section-4/lesson-1_WEBアプリをアップグレードしよう.md
  docs/ETH-NFT-Collection/ja/section-4/lesson-2_Vercelにアプリをデプロイしよう.md
  public/images/ETH-NFT-Collection/section-3/3_1_4.png
Labels: documentation

#415 Feature/AVAX-Messenger/refactor
  docs/AVAX-Messenger/ja/section-0/lesson-1_Avalancheネットワーク上でWEBアプリを構築しよう.md
  docs/AVAX-Messenger/ja/section-1/lesson-1_開発環境を用意しよう.md
  docs/AVAX-Messenger/ja/section-1/lesson-2_Solidityでスマートコントラクトを作成しよう.md
  docs/AVAX-Messenger/ja/section-1/lesson-3_メッセージの保存機能を実装しよう.md
  docs/AVAX-Messenger/ja/section-1/lesson-4_メッセージの確認機能を実装しよう.md
  docs/AVAX-Messenger/ja/section-1/lesson-5_イベントを追加しよう.md
  docs/AVAX-Messenger/ja/section-2/lesson-1_フロントエンドをセットアップしよう.md
  docs/AVAX-Messenger/ja/section-2/lesson-2_フロントエンドのベースを作成しよう.md
  docs/AVAX-Messenger/ja/section-2/lesson-3_フロントエンドとウォレットを連携しよう.md
  docs/AVAX-Messenger/ja/section-2/lesson-4_コントラクトをテストネットにデプロイしよう.md
  docs/AVAX-Messenger/ja/section-2/lesson-5_WEBアプリからコントラクトを呼び出そう.md
  docs/AVAX-Messenger/ja/section-3/lesson-1_コントラクトに管理者を設けよう.md
  docs/AVAX-Messenger/ja/section-3/lesson-2_フロントエンドを完成させよう.md
  docs/AVAX-Messenger/ja/section-4/lesson-1_Webアプリをデプロイしよう.md
  public/images/AVAX-Messenger/section-4/4_1_3.png
Labels: documentation, enhancement

#416 Feature/ICP-Basic-DEX/dfx upgrade
  docs/ICP-Basic-DEX/ja/section-0/lesson-1_プロジェクトの概要を掴もう.md
  docs/ICP-Basic-DEX/ja/section-0/lesson-2_環境構築をしよう.md
  docs/ICP-Basic-DEX/ja/section-1/lesson-1_オリジナルのトークンをデプロイしてみよう.md
  docs/ICP-Basic-DEX/ja/section-1/lesson-2_Faucet機能を実装しよう.md
  docs/ICP-Basic-DEX/ja/section-1/lesson-5_入金・出金機能をテストしてみよう.md
  docs/ICP-Basic-DEX/ja/section-2/lesson-3_取引機能をテストしてみよう.md
  public/images/ICP-Basic-DEX/section-0/0_2_2.png
Labels: documentation, enhancement

#420 Feature/AVAX-Asset-Tokenizasion/refactor
  docs/AVAX-Asset-Tokenization/ja/section-0/lesson-1_プロジェクトを開始しよう.md
  docs/AVAX-Asset-Tokenization/ja/section-1/lesson-1_開発環境を用意しよう.md
  docs/AVAX-Asset-Tokenization/ja/section-1/lesson-2_NFTコントラクトを作成しよう.md
  docs/AVAX-Asset-Tokenization/ja/section-1/lesson-3_メインコントラクトを作成しよう.md
  docs/AVAX-Asset-Tokenization/ja/section-2/lesson-1_フロントエンドをセットアップしよう.md
  docs/AVAX-Asset-Tokenization/ja/section-2/lesson-2_フロントエンドのベースを作成しよう.md
  docs/AVAX-Asset-Tokenization/ja/section-2/lesson-3_コントラクトと接続しよう.md
  docs/AVAX-Asset-Tokenization/ja/section-3/lesson-2_自動実行を実装しよう.md
  docs/AVAX-Asset-Tokenization/ja/section-3/lesson-3_Upkeepを登録しよう.md
  docs/AVAX-Asset-Tokenization/ja/section-4/lesson-1_Webアプリをデプロイしよう.md
  public/images/AVAX-Asset-Tokenization/section-1/1_1_3.png
  public/images/AVAX-Asset-Tokenization/section-1/1_1_4.png
  public/images/AVAX-Asset-Tokenization/section-3/2_1_12.png
  public/images/AVAX-Asset-Tokenization/section-4/4_1_3.png
Labels: documentation

#418 Feature/AVAX-AMM/refactor
  docs/AVAX-AMM/ja/section-0/lesson-1_プロジェクトを開始しよう.md
  docs/AVAX-AMM/ja/section-1/lesson-1_開発環境を用意しよう.md
  docs/AVAX-AMM/ja/section-1/lesson-2_Solidityでスマートコントラクトを作成しよう.md
  docs/AVAX-AMM/ja/section-1/lesson-3_流動性の提供を実装しよう.md
  docs/AVAX-AMM/ja/section-1/lesson-4_トークンの引出しを実装しよう.md
  docs/AVAX-AMM/ja/section-2/lesson-1_swapを理解しよう.md
  docs/AVAX-AMM/ja/section-2/lesson-3_swapを実装しよう.md
  docs/AVAX-AMM/ja/section-3/lesson-1_フロントエンドをセットアップしよう.md
  docs/AVAX-AMM/ja/section-3/lesson-2_フロントエンドのベースを作成しよう.md
  docs/AVAX-AMM/ja/section-3/lesson-3_コントラクトと接続しよう.md
  docs/AVAX-AMM/ja/section-3/lesson-4_フロントエンドを完成させよう.md
  docs/AVAX-AMM/ja/section-4/lesson-1_Webアプリをデプロイしよう.md
  public/images/AVAX-AMM/section-4/4_1_3.png
Labels: documentation

#422 fix: AVAX-Asset-Tokenization/change file name to .env
  docs/AVAX-Asset-Tokenization/ja/section-2/lesson-3_コントラクトと接続しよう.md
  docs/AVAX-Asset-Tokenization/ja/section-4/lesson-1_Webアプリをデプロイしよう.md
Labels: documentation

#421 Feature/AVAX-Subnet/refactor
  docs/AVAX-Subnet/ja/section-0/lesson-1_プロジェクトを開始しよう.md
  docs/AVAX-Subnet/ja/section-2/lesson-1_開発環境を用意しよう.md
  docs/AVAX-Subnet/ja/section-2/lesson-2_コントラクトを作成しよう.md
  docs/AVAX-Subnet/ja/section-3/lesson-1_開発環境を用意しよう.md
  docs/AVAX-Subnet/ja/section-3/lesson-2_フロントエンドのベースを作成しよう.md
  docs/AVAX-Subnet/ja/section-3/lesson-3_コントラクトと接続しよう.md
  docs/AVAX-Subnet/ja/section-4/lesson-1_プロジェクトをまとめましょう.md
Labels: documentation

#426 Fix/ETH-NFT-Collection
  docs/ETH-NFT-Collection/ja/section-2/lesson-3_ブロックチェーン上で動的なSVGを作ろう.md
  docs/ETH-NFT-Collection/ja/section-3/lesson-3_WEBアプリからコントラクトを呼び出そう.md
  docs/ETH-NFT-Collection/ja/section-4/lesson-1_WEBアプリをアップグレードしよう.md
Labels: bug, documentation

#427 Update description.json
  public/metadata/ETH-Yield-Farm/description.json
Labels: documentation
